//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TargetPoker.Dados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class targetpokerEntities : DbContext
    {
        public targetpokerEntities()
            : base("name=targetpokerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<evento> evento { get; set; }
        public DbSet<jogador> jogador { get; set; }
        public DbSet<tipoevento> tipoevento { get; set; }
        public DbSet<torneio_jogador> torneio_jogador { get; set; }
    }
}
