//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TargetPoker.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        public evento()
        {
            this.torneio_jogador = new HashSet<torneio_jogador>();
        }
    
        public int id_evento { get; set; }
        public int id_tipo_evento { get; set; }
        public string ds_titulo { get; set; }
        public string ds_torneio { get; set; }
        public System.DateTime dt_torneio { get; set; }
        public string ds_local { get; set; }
        public Nullable<decimal> vl_buy_in { get; set; }
        public Nullable<decimal> vl_rake { get; set; }
        public Nullable<decimal> vl_total_premiacao { get; set; }
        public Nullable<int> qt_minima_jogador { get; set; }
        public Nullable<int> qt_maxima_jogador { get; set; }
    
        public virtual tipoevento tipoevento { get; set; }
        public virtual ICollection<torneio_jogador> torneio_jogador { get; set; }
    }
}
