//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TargetPoker.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoevento
    {
        public tipoevento()
        {
            this.evento = new HashSet<evento>();
        }
    
        public int id_tipo_evento { get; set; }
        public string ds_evento { get; set; }
    
        public virtual ICollection<evento> evento { get; set; }
    }
}
